/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry_rpl;

import com.mysql.jdbc.Driver;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author asus
 */
public class loginOwner extends javax.swing.JFrame {
    private Connection conn;
    private Statement st;
    ResultSet rs;
    String sql="";

    /**
     * Creates new form loginOwner
     */
    public loginOwner() throws SQLException {
        initComponents();
        this.conn = new koneksi().getkoneksi();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInBtn = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnSignup1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sign_up_btn = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelusername = new javax.swing.JLabel();
        labelpass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(255, 255, 255));
        signInBtn.setText("SIGN IN");
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });
        getContentPane().add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 70, 40));

        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 310, 30));

        txtUsername.setBorder(null);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 300, 30));

        btnSignup1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnSignup1.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup1.setText("Admin");
        btnSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignup1MouseClicked(evt);
            }
        });
        getContentPane().add(btnSignup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 70, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login as");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 80, 40));

        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 11.png"))); // NOI18N
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 220, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Don't have an account?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, -1, -1));

        Sign_up_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        Sign_up_btn.setForeground(new java.awt.Color(153, 0, 204));
        Sign_up_btn.setText("Sign Up");
        Sign_up_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_up_btnMouseClicked(evt);
            }
        });
        getContentPane().add(Sign_up_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        exit.setText("jLabel2");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pass icon.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 40, 40));

        labelusername.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(labelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 230, 20));

        labelpass.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(labelpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 230, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user icon_2.png"))); // NOI18N
        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 10.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        String user = txtUsername.getText();
        String pass = txtPassword.getText();
        try{
            if(user.isEmpty()){
                labelusername.setText("Masukkan username anda !!");
            }else{
                labelusername.setText("");
                try {
            Connection k = koneksi.getkoneksi();
            Statement s = k.createStatement();
            ResultSet r = s.executeQuery("SELECT * FROM user WHERE username='"+txtUsername.getText()+"' or password='"+txtPassword.getText()+"' AND akses = 'Owner'");
            if (r.next()){
                if (txtPassword.getText().equals(r.getString ("password"))&&(txtUsername.getText().equals(r.getString("username")))){
                    this.dispose();
                    new DashboardOwner().setVisible(true);
                    
                }else{
//                    JOptionPane.showMessageDialog(null, "Username dan Password Salah");
                }
                if (txtPassword.getText().equals(r.getString("password"))) {
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Password Salah");
                }
                if (txtUsername.getText().equals(r.getString("username"))) {
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Username Salah");
                }txtPassword.setText("");
        
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "terjadi kesalahan");
        }
            }if(pass.isEmpty()){
                labelpass.setText("Masukkan password anda !!");
            }else{
                labelpass.setText("");               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
//            
    }//GEN-LAST:event_signInBtnMouseClicked

    private void Sign_up_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_up_btnMouseClicked
        this.dispose();
        Register r = null;
        try {
            r = new Register();
        } catch (SQLException ex) {
            Logger.getLogger(loginOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
        r.setVisible(true);
    }//GEN-LAST:event_Sign_up_btnMouseClicked

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        this.dispose();
        Register r = null;
        try {
            r = new Register();
        } catch (SQLException ex) {
            Logger.getLogger(loginOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
        r.setVisible(true);
    }//GEN-LAST:event_btnSignupMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        if(JOptionPane.showConfirmDialog(null,"Exit","U-Laundry", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void btnSignup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignup1MouseClicked
        this.dispose();
        loginAdmin r = null;
        try {
            r = new loginAdmin();
        } catch (SQLException ex) {
            Logger.getLogger(loginOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
        r.setVisible(true);
    }//GEN-LAST:event_btnSignup1MouseClicked

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        String user = txtUsername.getText();
        
        if(user.isEmpty()){
                labelusername.setText("Masukkan username anda !!");
            }else{
                labelusername.setText("");
            }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        String pass = txtPassword.getText();
        
        if(pass.isEmpty()){
                labelpass.setText("Masukkan password anda !!");
            }else{
                labelpass.setText("");
            }
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginOwner().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(loginOwner.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sign_up_btn;
    private javax.swing.JLabel btnSignup;
    private javax.swing.JLabel btnSignup1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelpass;
    private javax.swing.JLabel labelusername;
    private javax.swing.JLabel signInBtn;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
